spring:
  datasource:
    url: jdbc:h2:/home/ilia/home/IliaLessons/db/testDB
    driver-class-name: org.h2.Driver
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

data-storage:
  active: JPA